# Generated by Django 5.0.6 on 2026-05-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0002_valorreferencia_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorreferencia',
            options={'ordering': ['hormona', 'version', 'grupo_clinico'], 'verbose_name': 'Valor de referencia', 'verbose_name_plural': 'Valores de referencia'},
        ),
        migrations.AlterUniqueTogether(
            name='valorreferencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='grupo_clinico',
            field=models.CharField(blank=True, help_text='Ej: Hombres, Mujeres Fase Folicular, Hombres (20-49 años)', max_length=100, verbose_name='Grupo / Condición clínica'),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='ref_max2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Ref. máx (unidad 2)'),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='ref_min2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Ref. mín (unidad 2)'),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='tipo_muestra',
            field=models.CharField(blank=True, help_text='Ej: Suero y Plasma, Suero', max_length=100, verbose_name='Tipo de muestra'),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='unidad2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unidad 2'),
        ),
        migrations.AlterField(
            model_name='valorreferencia',
            name='intervalo_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Intervalo máx (técnico)'),
        ),
        migrations.AlterField(
            model_name='valorreferencia',
            name='intervalo_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Intervalo mín (técnico)'),
        ),
        migrations.AlterField(
            model_name='valorreferencia',
            name='ref_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Ref. máx'),
        ),
        migrations.AlterField(
            model_name='valorreferencia',
            name='ref_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Ref. mín'),
        ),
        migrations.AlterField(
            model_name='valorreferencia',
            name='unidad',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unidad 1'),
        ),
        migrations.AlterField(
            model_name='valorreferencia',
            name='version',
            field=models.CharField(max_length=50, verbose_name='Versión del inserto'),
        ),
        migrations.AlterUniqueTogether(
            name='valorreferencia',
            unique_together={('hormona', 'version', 'grupo_clinico')},
        ),
    ]
