# Generated by Django 5.0.6 on 2026-05-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], db_index=True, default='pendiente', max_length=15),
        ),
    ]
