# Generated by Django 5.0.6 on 2026-05-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_hipogonadismo_na'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_procedimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de procedimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hormonas_ihq',
            field=models.CharField(blank=True, help_text='Valores separados por coma: prl,gh,acth,fsh_lh,tsh', max_length=100, verbose_name='Hormonas IHQ'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ki67_interp',
            field=models.CharField(blank=True, choices=[('', '—'), ('muy_bajo', 'Muy bajo (< 1 %)'), ('bajo', 'Bajo (1 – 3 %)'), ('alto', 'Alto (> 3 %)'), ('muy_alto', 'Muy alto (>= 10 %)')], max_length=10, verbose_name='Interpretación Ki-67'),
        ),
    ]
