[uwsgi]
socket=/home/herzendo_app/uwsgi/uwsgi_app.sock
chdir = /home/herzendo_app
module=herzendo.wsgi:application
master=true
chmod-socket=666
uid=www-data
gid=www-data
vacuum=true
# Increase the internal buffer size for large request headers (default is 4096)
buffer-size = 32768