# Generated by Django 5.0.6 on 2026-05-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hormona', models.CharField(choices=[('gh', 'GH'), ('igf1', 'IGF1'), ('lh', 'LH'), ('fsh', 'FSH'), ('estradiol', 'ESTRADIOL'), ('testosterona', 'Testosterona'), ('tsh', 'TSH'), ('ft4', 'FT4'), ('cortisol', 'Cortisol'), ('acth', 'ACTH'), ('prolactina', 'PROLACTINA')], max_length=20)),
                ('version', models.CharField(max_length=20, verbose_name='Versión del inserto')),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('ref_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Ref. mín (teórico)')),
                ('ref_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Ref. máx (teórico)')),
                ('intervalo_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Intervalo mín (técnico)')),
                ('intervalo_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Intervalo máx (técnico)')),
            ],
            options={
                'verbose_name': 'Valor de referencia',
                'verbose_name_plural': 'Valores de referencia',
                'ordering': ['hormona', 'version'],
                'unique_together': {('hormona', 'version')},
            },
        ),
    ]
