# Generated by Django 5.0.6 on 2026-05-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorreferencia',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
